version: '3.8'

volumes:
  database-data:
    driver: local

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    user: "1000:1000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: sde
    ports:
      - 27017:27017
    volumes:
      - ./volumes/database-data:/data/db

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/sde?authSource=admin&readPreference=primary&ssl=false&directConnection=true
    #      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

  backend-server:
    build: ./backend
    image: backend_image
    container_name: sde-backend_server
    develop:
      watch:
        - action: rebuild
          source: .
          target: .
          ignore:
            - node_modules
            - volumes
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ./volumes/songs:/media
  
  spleeter-lib:
    build: ./spleeter
    image: spleeter_image
    container_name: sde-spleeter_lib
    ports: 
      - 5000:5000
    volumes:
      - ./volumes/songs:/media

